### ISSUE TITLE
Resource Packs error?

### ISSUE THREAD

**Issue by addpromax** [GeyserExtras/GeyserExtras#8]
![image](https://github.com/user-attachments/assets/c74329f5-8343-4519-bfe5-e2e900fa4ce3)

**Comment by addpromax** [comment]
No error
Install plugins: https://mclo.gs/QFrPuoF

**Comment by letsgoawaydev** [comment]
not really sure what plugin could be causing this, but its probably one of them. You could also try redownloading the jar, but its likely that 2.0 fixes this anyway because it uses direct bedrock packets to send the titles, meaning that Java plugins shouldnt be able to mess it up. But other than that I cant really help

**Comment by addpromax** [comment]
sorry. I will try again
